"""Local privacy-proof artifacts for Zama and Aztec integration lanes."""

from __future__ import annotations

import hashlib
import json
from dataclasses import asdict, dataclass
from typing import Any


@dataclass(frozen=True)
class LocalProofArtifact:
    engine: str
    status: str
    artifact_path: str
    public_claim: str
    public_inputs: dict[str, Any]
    private_witness_redacted: tuple[str, ...]
    exported_commitment: str
    receipt_binding: dict[str, str]
    next_verifier_step: str
    constraints: tuple[str, ...]

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(frozen=True)
class PrivacyProofBundle:
    status: str
    live_proving_enabled: bool
    claim_boundary: str
    artifacts: tuple[LocalProofArtifact, ...]

    def to_dict(self) -> dict[str, Any]:
        return {
            "status": self.status,
            "live_proving_enabled": self.live_proving_enabled,
            "claim_boundary": self.claim_boundary,
            "artifacts": [artifact.to_dict() for artifact in self.artifacts],
        }


def build_privacy_proof_bundle(
    *,
    policy_hash: str,
    resource_hash: str,
    result_hash: str,
    risk_hash: str,
    privacy_commitment: str,
    amount_atomic: int,
    approved: bool,
) -> PrivacyProofBundle:
    """Build deterministic local proof artifacts for the judge demo.

    These are not real Zama ciphertexts or Aztec proofs. They are local,
    reproducible witness/commitment envelopes that pin down what each privacy
    layer would prove and what public value Sentinel would anchor.
    """

    zama_private = {
        "spend_remaining_atomic": 1_630_000,
        "requested_amount_atomic": amount_atomic,
        "risk_score_bps": 214,
        "max_risk_bps": 500,
        "single_issuer_bps": 1920,
        "max_single_issuer_bps": 2500,
    }
    zama_public = {
        "policy_hash": policy_hash,
        "resource_hash": resource_hash,
        "approved": approved,
        "requested_amount_atomic": str(amount_atomic),
        "max_risk_bps": str(zama_private["max_risk_bps"]),
    }
    encrypted_input_commitment = _commit("zama-encrypted-input-v1", zama_private)
    zama_export = _commit(
        "zama-risk-commitment-v1",
        {
            "encrypted_input_commitment": encrypted_input_commitment,
            "policy_hash": policy_hash,
            "resource_hash": resource_hash,
            "approved": approved,
        },
    )

    aztec_private = {
        "private_mandate_secret": "redacted",
        "private_user_salt": "redacted",
        "private_balance_atomic": 3_200_000,
        "private_risk_score_bps": 214,
    }
    aztec_public = {
        "policy_hash": policy_hash,
        "resource_hash": resource_hash,
        "result_hash": result_hash,
        "public_max_risk_bps": "500",
        "public_min_balance_atomic": str(amount_atomic),
    }
    aztec_export = _commit(
        "aztec-private-intent-v1",
        {
            **aztec_public,
            "private_balance_passed": aztec_private["private_balance_atomic"] >= amount_atomic,
            "private_risk_passed": aztec_private["private_risk_score_bps"] <= 500,
        },
    )

    return PrivacyProofBundle(
        status="local_artifact_ready",
        live_proving_enabled=False,
        claim_boundary=(
            "Local deterministic proof artifacts only; no live Zama ciphertext or Aztec proof "
            "is generated by the default demo."
        ),
        artifacts=(
            LocalProofArtifact(
                engine="Zama fhEVM",
                status="local_mock_artifact",
                artifact_path="contracts/privacy/EncryptedRiskGateMock.sol",
                public_claim="Encrypted spend and risk values satisfy the public mandate thresholds.",
                public_inputs={
                    **zama_public,
                    "encrypted_input_commitment": encrypted_input_commitment,
                },
                private_witness_redacted=(
                    "exact spend history",
                    "raw risk score",
                    "single-issuer concentration",
                ),
                exported_commitment=zama_export,
                receipt_binding={
                    "risk_hash": risk_hash,
                    "privacy_commitment": privacy_commitment,
                },
                next_verifier_step="Port the mock interface to Zama encrypted integer types on Sepolia.",
                constraints=(
                    "not native Robinhood Chain FHE",
                    "no ciphertext is submitted in the default demo",
                ),
            ),
            LocalProofArtifact(
                engine="Aztec",
                status="noir_blueprint_artifact",
                artifact_path="artifacts/privacy/aztec_private_intent_note.nr",
                public_claim="A private balance and intent note can satisfy public risk and balance thresholds.",
                public_inputs=aztec_public,
                private_witness_redacted=(
                    "private mandate secret",
                    "user salt",
                    "private balance",
                    "private risk score",
                ),
                exported_commitment=aztec_export,
                receipt_binding={
                    "result_hash": result_hash,
                    "privacy_commitment": privacy_commitment,
                },
                next_verifier_step="Run a local Noir proof once the Aztec toolchain is installed.",
                constraints=(
                    "Aztec is not EVM-compatible",
                    "exported commitment is anchored publicly by Sentinel",
                ),
            ),
        ),
    )


def _commit(label: str, payload: dict[str, Any]) -> str:
    raw = json.dumps(
        {"label": label, "payload": payload},
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    return "0x" + hashlib.sha256(raw).hexdigest()
